[timeseries]
meteo = "examples/reproduction_volkerak_2018//input/meteo"
discharge = "examples/reproduction_volkerak_2018/input/discharge"
chloride= "examples/reproduction_volkerak_2018/input/chloride"
pumps_wb = "examples/reproduction_volkerak_2018//input/pumps"
inlaat_wb = "examples/reproduction_volkerak_2018//input/inlaat"
pumps_balance = "P:/11212800-002/2. Calculations/rgwm_versie2.5.0/examples/VZM/output"
inlaat_balance = "P:/11212800-002/2. Calculations/rgwm_versie2.5.0/examples/VZM/output"
pumps_wb_out = "examples/reproduction_volkerak_2018/input/params/VZM_pumps.csv"
inlaat_wb_out = "examples/reproduction_volkerak_2018/input/params/VZM_inlaat.csv"
params =  "examples/reproduction_volkerak_2018/input/params"

[season]
summer_months = ["April", "May", "June", "July", "August", "September"]
winter_months = ["October","November","December","January","February","March"]
min_per_24h = 1440

[output]
output = "examples/reproduction_volkerak_2018/output"

[const_fluxes]
leakage = "examples/reproduction_volkerak_2018/input/const_fluxes/leakage.csv"
lock_operations = "examples/reproduction_volkerak_2018/input/const_fluxes/lock_operations.csv"
up_grndwater_flux = "examples/reproduction_volkerak_2018/input/const_fluxes/up_grndwater_flux.csv"

[balance]
balance = "True"